# Generated by Django 3.2.9 on 2021-12-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=70, verbose_name='Full Name')),
                ('occupation', models.CharField(max_length=256, verbose_name='Occupation')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, verbose_name='Sex')),
                ('id_number', models.IntegerField(verbose_name='ID Number')),
                ('image', models.ImageField(upload_to='photos')),
            ],
        ),
    ]
